[package]
name = "rheinfall"
version = "1.0.0"
authors = ["Simon Ellmann <kontakt@simonellmann.de>"]
edition = "2018"

[dependencies]
redox_event = { git = "https://gitlab.redox-os.org/redox-os/event.git" }
redox_syscall = "0.1"
